services:
  redis:
    image: redis:7-alpine
    container_name: horizon-redis
    restart: unless-stopped
    command: redis-server --requirepass 081e7c1083c3dee0b443c44f2398e39d
    networks:
      - horizon-internal
    volumes:
      - redis-data:/data

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: horizon-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./data/dev:/app/data
    depends_on:
      - redis
    networks:
      - horizon-internal

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: horizon-test
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.test
    volumes:
      - ./data/test:/app/data
    depends_on:
      - redis
    networks:
      - horizon-internal

  acceptance:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: horizon-acceptance
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env.acceptance
    volumes:
      - ./data/acceptance:/app/data
    depends_on:
      - redis
    networks:
      - horizon-internal

networks:
  horizon-internal:
    driver: bridge

volumes:
  redis-data: